spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      mvc:
        routes:
          - id: user-service
            uri: ${USER_SERVICE_URL}
            predicates:
              - Path=/api/users/**
            filters:
              - StripPrefix=0

          - id: auth-service
            uri: ${AUTH_SERVICE_URL}
            predicates:
              - Path=/api/auth/**
            filters:
              - StripPrefix=0

          - id: report-service
            uri: ${REPORT_SERVICE_URL}
            predicates:
              - Path=/api/report/**,/api/squad/reports/**,/api/new/**
            filters:
              - StripPrefix=0

          - id: inventory-service
            uri: ${INVENTORY_SERVICE_URL}
            predicates:
              - Path=/api/inventory/**
            filters:
              - StripPrefix=0
server:
  port: ${PORT:8080}

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}